### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/tmp/kaniko-action-l5i4IS/digest'

### ISSUE THREAD

**Issue by airabia** [int128/kaniko-action#347]
Hello, 
I am using actions-runner-controller in a Kubernetes cluster. When I deploy the kaniko action to these runners, and I get this error:
Error: ENOENT: no such file or directory, open '/tmp/kaniko-action-l5i4IS/digest'
 
Even we get this error, the other things about kaniko-action are perfectly running, like the action is building and sending the image to ecr. That's why we can use continue-on-error: true to ignore it, but it is not useful for us considering the other build errors. 

Probably related to the problem, I got this error because kaniko actions didn't create a sub-directory inside the runner pods. Since the name of the sub-directory is constantly changing, I cannot create this directory as a separate step in the workflow.
Our action step is (just related parts):

      - uses: int128/create-ecr-repository-action@v1
        id: ecr-cache
        with:
          repository: example/repo/service/cache

     - name: Build and push service
        id: docker_build-service
        uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.meta_service.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: ./service/
          cache: true
          cache-repository: ${{ steps.ecr-cache.outputs.repository-uri }}

**Comment by airabia** [comment]
For a quick solution, can we have digest output as an option?

**Comment by int128** [comment]
Could you try the DinD runner?
https://github.com/actions/actions-runner-controller/blob/84104de74b8e9e555f530d40d8f33cc9471716f5/docs/detailed-docs.md#runner-with-dind

This action creates a directory `/tmp/kaniko-action-*` and mount it into the Kaniko container.

https://github.com/int128/kaniko-action/blob/56da17a795971ef54103b302c5f1bb06287c2cdb/src/run.ts#L32 https://github.com/int128/kaniko-action/blob/56da17a795971ef54103b302c5f1bb06287c2cdb/src/run.ts#L57-L58

By default actions-runner-controller creates a pod with runner container and Docker container.
I think Docker container cannot mount the directory because it is in the runner container.
For DinD runner, both runner and Docker are running in the same container, so it may resolve this issue.

**Comment by int128** [comment]
I noticed that it is preferred to use `RUNNER_TEMP` instead of the OS temporary directory.
https://docs.github.com/en/actions/learn-github-actions/environment-variables

I changed the temporary directory as #351. Could you try again?

**Comment by airabia** [comment]
@int128 thank you for your quick help. The problem has been fixed with your change! Action is running on both gitHub-runner server and actions-runner-controller smoothly.  Also, I will look at the interesting DinD concept as well.

**Comment by int128** [comment]
Thank you for the nice issue!
